### ISSUE TITLE
Add a link from the repo to the running example

### ISSUE THREAD

**Issue by kwalrath** [angular/dart-doc-syncer#11]
The README.md files (e.g. [structural-directives's README](https://github.com/angular-examples/structural-directives/blob/master/README.md)) currently say something like this:

> Welcome to the example application used in angular.io/dart's
> [structural-directives](//github.com/angular/angular.io/tree/master/public/docs/_examples/structural-directives/dart) page.
> 
> To run your own copy:

I'd like to add a prominent link to where they can find the already built version. Something like this:

> Welcome to the example application used in angular.io/dart's
> [structural-directives](//github.com/angular/angular.io/tree/master/public/docs/_examples/structural-directives/dart) page.
> To run this app, go to http://angular-examples.github.io/structural-directives.
> 
> To get the source code and run your own copy:

**Comment by chalin** [comment]
Closed by #13
