### ISSUE TITLE
Make test deployments easy

### ISSUE THREAD

**Issue by kwalrath** [angular/dart-doc-syncer#18]
@chalin has sometimes run dart-doc-syncer before tests have passed, because dds is faster than the tests, and being able to visit the running apps makes spot checking is easy.

It'd be nice if it were easy to automate a local-only version of dds. So... thinking of what'd be necessary... you'd copy all the files locally and start a server, plus you'd have a list of all the examples so it'd be easy to spot check them.

Perhaps this could be added to `--dry-run`?

Which reminds me... we should document the command-line options in the README. I can do that.

**Comment by chalin** [comment]
You can use `--no-push`.

**Comment by chalin** [comment]
You can use either/or `--dry-run` and/or `--no-push`. The former doesn't actually build any of the apps. The latter, builds the apps but doesn't do the final step of pushing to the example repos. Most often I'll use `--no-push` in conjunction with `--keep-tmp`, which will allow me to inspect the built apps after dds is done.

The cmd line options are documented:
```
------------------------------------------------------------------

Syncs Angular docs example applications..

Usage: dart_doc_syncer [options] [<exampleName> | <examplePath> <exampleRepo>]

-h, --help           show this usage information
-b, --branch         <branch-name>
                     git branch to fetch examples from
                     (defaults to "master")

-n, --dry-run        show which commands would be executed but make (almost) no changes;
                     only the temporary directory will be created

-f, --force-build    forces build of example app when sources have not changed
-k, --keep-tmp       do not delete temporary working directory (.tmp) once done
-p, --[no-]push      prepare updates and push to example repo
                     (defaults to on)

-m, --match          <dart-regexp>
                     sync all examples having a data file (.docsync.json)
                     and whose repo path matches the given regular expression;
                     use "." to match all

-u, --user           <user-id>
                     GitHub id of repo to fetch examples from
                     (defaults to "dart-lang")

-v, --verbose        

------------------------------------------------------------------
```

Closing this since I believe that the original concerns have been addressed. If not, let me know.
