### ISSUE TITLE
Craft a better, more appealing README for generated examples.

### ISSUE THREAD

**Issue by thso** [angular/dart-doc-syncer#2]
Link to other interesting examples or where a complete list can be found.
Links to other good reads about the subject?
Point to installation instructions for Angular, Dart?

**Comment by kwalrath** [comment]
I'm not great with making it appealing, but I have a few suggestions for content.
- Mention Angular 2 & Dart somewhere.
- Enable specifying a link URL and link text for where the example is used. (Would this be in the pubspec or in a separate config file?) You could call them homepageName & homepageUrl, with homepageName being optional.
- Enable specifying "see also" links, ideally with optional link text as well as URLs.
- Make it possible to have an example even if there's no page to explain it yet. Maybe just skip the first sentence if there's no homepageUrl?
- Host the running example (and link to it). This could be in v2.

Maybe:

---

# Template Syntax

Welcome to the example application used in angular.io/dart's [Template Syntax](https://angular.io/docs/dart/latest/guide/template-syntax.html) page.

_OR, if there's no link name:_
Welcome to the example application used in https://angular.io/docs/dart/latest/guide/template-syntax.html.

You can [run a hosted copy of this sample](http://example.com). Or run your own copy:
1. Clone this repo.
2. Download the dependencies.  
   `pub get`
3. Launch a development server.  
   `pub serve`
4. Open a browser to `http://localhost:8080`.  
   In Dartium, you'll see the app right away.
   In other modern browsers, you'll have to wait a bit while pub converts the app to JavaScript.

See also:
- [link 1](http://example.com)
- [link 2](http://example.com)
- [link 3](http://example.com)
- [Angular 2 docs for Dart](http://angular.io/dart)
