### ISSUE TITLE
Fix README.md formatting

### ISSUE THREAD

**Issue by chalin** [angular/dart-doc-syncer#24]
E.g., see https://github.com/angular-examples/quickstart/blob/master/README.md looks like this:
> You can run a hosted copy of this sample. Or run your own copy:
>
> Clone or [download][] this repo. [download]: //github.com/angularexamples/quickstart/archive/master.zip
> Get the dependencies:
> pub get 3. Launch a development server:
> pub serve 4. Open a browser to http://localhost:8080.

cc @kwalrath

**Comment by kwalrath** [comment]
Yes, I noticed that in other markdown files (in the stagehand wiki, iirc). It seems that GitHub has changed how it treats triple-` blocks in lists.

I tried a bit yesterday to fix this but gave up when I didn't immediately figure it out. (I hoped that it would just fix itself.)

**Comment by kwalrath** [comment]
I've filed https://github.com/github/markup/issues/1018.

**Comment by chalin** [comment]
I got the impression that maybe they've changed markdown processor (or processor version).

**Comment by kwalrath** [comment]
Yep, that was my assumption. Perhaps we're just the first to scream.

**Comment by kwalrath** [comment]
https://github.com/angular-examples/quickstart/pull/1 has the diffs we need.

**Comment by chalin** [comment]
The new syntax we need to conform to is: [CommonMark](http://commonmark.org).
* https://githubengineering.com/a-formal-spec-for-github-markdown/
* https://github.com/github/markup/issues/1018
