### ISSUE TITLE
Include more information in generated commit message.

### ISSUE THREAD

**Issue by thso** [angular/dart-doc-syncer#3]
Sync with 3b768a3  

Synced with angular/angular.io master branch, commit 3b768a3:  
[public/docs/_examples/template-syntax/dart](https://github.com/angular/angular.io/tree/3b768a341c9d550530f50d69b31a39b60d0812cc/public/docs/_examples/template-syntax/dart).

**Comment by kwalrath** [comment]
A couple of tweaks: 
- Delete the final "."
- Remove whatever is causing the blank line before the last line.
