### ISSUE TITLE
For Angular 5, build using dart2js

### ISSUE THREAD

**Issue by chalin** [angular/dart-doc-syncer#39]
Under the new build system, dartdevc is the default web compiler. Until dartdevc is recommended for use in production, continue to using dart2js -- in particular, because dartdevc deploy don't currently work :), see https://github.com/dart-lang/build/issues/896.

This is the DDS request for https://github.com/dart-lang/site-webdev/issues/1284.

**Comment by matanlurey** [comment]
> Until dartdevc is recommended for use in production

This will never be the case, hence the word `dev`.

**Comment by chalin** [comment]
Ok :)
