### ISSUE TITLE
Reduce/clarify command output

### ISSUE THREAD

**Issue by kwalrath** [angular/dart-doc-syncer#4]
I'd like to see much less output from `dart bin/sync_all.dart` — just an indication of which directories it looked at, which repos it updated, and whether it succeeded or failed. Something like this:

```
Source repo: https://github.com/angular/angular.io
Processing public/docs/_examples/template-syntax
  Sample changed!
  Updating repo: https://github.com/angular-examples/template-syntax
Processing public/docs/_examples/pipes
  No changes.
Processing public/docs/_examples/server-communication
  No changes.
...
Processed 10 samples.
Updated 1 repo.
```

Details:
When I ran `dart bin/sync_all.dart` today, I got 117 lines of output. Most of it is prefixed with FINE, a bit of it is prefixed with SEVERE. I initially took "FINE" as meaning "OK" and "SEVERE" as meaning "OMG: ERROR!". 

Also, every example has a line like this:

```
FINE: 2016-04-21 09:02:31.946215: Pushing generated example to git@github.com:angular-examples/template-syntax.git.
```

But it's not really pushing unless it also has a message like this:

```
FINE: 2016-04-21 09:02:31.976059: Pushing changes for /Users/kathyw/GITHUB/dart-doc-syncer/bin/.tmp/template-syntax.
```

I had to look at the actual repos to see whether they were updated.

Also the current output has a misspelling: "Comitting". :)

**Comment by kwalrath** [comment]
I got my wish: There's much less output. Unfortunately, now there's so little output that you don't know which sample it's working on and whether it's updating master, gh-pages, or neither.

The only output you see (unless you type in a bad passphrase) is:

```
Enter passphrase for key '<path to rsa file>': 
Enter passphrase for key '<path to rsa file>': 
Enter passphrase for key '<path to rsa file>': 
...
```

The first time through, I assumed I'd typed it in wrong, since it asked me again. :)

I'd love to (1) only enter the passphrase once and (2) have output that reflects which sample it's working on and which branches of the sample repo (if any) it has updated. So, to slightly alter what I originally suggested, how about this:

```
Enter passphrase for key '<path to rsa file>': 
Source repo: https://github.com/angular/angular.io
Processing public/docs/_examples/template-syntax
  Sample code changed!
  Updating repo: https://github.com/angular-examples/template-syntax (master and gh-pages)
Processing public/docs/_examples/pipes
  No sample code changed, but the compiled version changed.
  Updating repo: https://github.com/angular-examples/pipes (gh-pages)
Processing public/docs/_examples/server-communication
  No changes.
...
Processed 10 samples.
Updated 2 repos.
```

**Comment by thso** [comment]
Thanks for the update, will very soon work on giving better feedback on what's going on.

**Comment by thso** [comment]
Fixed by https://github.com/angular/dart-doc-syncer/commit/13d26ce53e268cd96f3faca75f652ad5c509c1a8
