### ISSUE TITLE
Add guide/component-styles example

### ISSUE THREAD

**Issue by chalin** [angular/dart-doc-syncer#7]
Once https://github.com/angular/angular.io/pull/1320 is merged.

**Comment by chalin** [comment]
Done: https://github.com/angular-examples/component-styles/commit/ebc048356db84dbf9203688e1bc536a89034e647.

**Comment by kwalrath** [comment]
I thought this example was broken until I ran the [TS version](https://angular.io/resources/live-examples/component-styles/ts/plnkr.html). It has the same boring output. :)
